version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - nginx-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/nginx_status']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  nginx-network:
    driver: overlay
    attachable: true
