version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - nginx-network
      - monitoring-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/nginx_status']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    ports:
      - '9113:9113'
    command:
      - '-nginx.scrape-uri=http://nginx:80/nginx_status'
    depends_on:
      - nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    networks:
      - nginx-network
      - monitoring-network
    # Healthcheck temporaneamente disabilitato per debug
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9113/metrics"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 45s

networks:
  nginx-network:
    driver: overlay
    attachable: true
  monitoring-network:
    driver: overlay
    external: true
